# .devcontainer/docker-compose.yml
services:
  # Your application development container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    # Mount your project directory into the container
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached

    # Keep the container running
    command: sleep infinity

    # Environment variables for the app, forwarded from devcontainer.json
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  # Your PostgreSQL database service
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data: # Persists database data across rebuilds